# --------------------------------------------
# CodeRabbit AI Review – CavalryFight設定
# --------------------------------------------

# レビューコメントの言語
language: ja

# AI の振る舞いに関する基本設定
reviews:
  # コメントが多すぎるとノイズになるため、精度重視で抑える
  comment_style: concise

  # めちゃ小さな差分までコメントしない
  min_lines_changed: 3

  # コメントのカテゴリを整える（読みやすさ向上）
  drafting:
    summary: true
    explanations: true
    suggestions: true

  # リスク系は強めに指摘してもらう
  focus:
    - security
    - performance
    - architecture
    - maintainability
    - readability
    - best-practices

  # コメントの最大数を制御（スパム防止）
  limits:
    max_comments: 25

# CavalryFight固有のコーディング規則チェック
custom_rules:
  # MVVMパターンの遵守
  - name: "MVVM Pattern Compliance"
    description: "Model/View/ViewModelの責務分離を確認"
    pattern: "Model|View|ViewModel"
    severity: warning
    message: "MVVMパターンに従っているか確認してください。Docs/CODING_RULES.mdを参照。"

  # Nullable参照型の使用
  - name: "Nullable Reference Types"
    description: "ViewModelでNullable参照型が有効か確認"
    pattern: "ViewModel"
    severity: warning
    message: "ViewModelには#nullable enableを使用してください。"

  # Regionsの使用
  - name: "Regions Organization"
    description: "Regionsでコードが整理されているか確認"
    pattern: "#region"
    severity: info
    message: "Regionsを使用してコードを整理してください（Fields, Properties, Unity Lifecycle等）。"

  # XMLドキュメントコメント
  - name: "XML Documentation"
    description: "public/protected/internalメンバーにXMLコメントがあるか確認"
    pattern: "public |protected |internal "
    severity: warning
    message: "public/protected/internalメンバーにはXMLドキュメントコメント（///）が必須です。"

  # Namespace規則
  - name: "Namespace Convention"
    description: "Namespaceが規則に従っているか確認"
    pattern: "namespace CavalryFight"
    severity: warning
    message: "Namespaceは CavalryFight.{Layer}.{Feature} の形式に従ってください。"

# 特定ファイルはレビュー対象から除外してノイズ削減
exclude:
  # Unity生成ファイル
  - "**/Library/**"
  - "**/Temp/**"
  - "**/Obj/**"
  - "**/Build/**"
  - "**/Builds/**"
  - "**/Logs/**"
  - "**/UserSettings/**"
  - "**/MemoryCaptures/**"
  - "**/Recordings/**"
  - "**/ProjectSettings/**"
  - "**/.vs/**"
  - "**/.vscode/**"
  - "**/.idea/**"

  # Unity固有ファイル
  - "**/*.meta"
  - "**/*.unitypackage"
  - "**/*.csproj"
  - "**/*.sln"
  - "**/*.unityproj"

  # アセットファイル（レビュー不要）
  - "**/*.png"
  - "**/*.jpg"
  - "**/*.jpeg"
  - "**/*.gif"
  - "**/*.psd"
  - "**/*.fbx"
  - "**/*.obj"
  - "**/*.blend"
  - "**/*.wav"
  - "**/*.mp3"
  - "**/*.ogg"

  # テスト生成ファイル
  - "**/InitTestScene*.unity"
  - "**/TestRunner/**"

# CI などで生成されるコードのレビューをスキップ
skip_generated_files: true

# PR に対する反応設定
pull_requests:
  enabled: true
  drafts: false
  auto_review_on_open: true
  auto_review_on_revise: true
  review_summary_comment: true

  # PR説明の改善提案
  suggest_pr_description: true

  # コーディング規則チェックリストのリマインド
  check_coding_standards: true

# セキュリティ強化チェック
security:
  dependency_scan: true
  secret_detection: true

  # Unity固有のセキュリティチェック
  check_for:
    - hardcoded_credentials
    - insecure_random
    - command_injection
    - xss_vulnerabilities

# パフォーマンスチェック強化
performance:
  # Unity固有のパフォーマンスアンチパターン
  check_for:
    - frequent_getcomponent_calls
    - update_loop_allocations
    - string_concatenation_in_loops
    - camera_main_in_update
    - find_operations_in_update

# コード品質チェック
code_quality:
  # 複雑度チェック
  max_method_lines: 50
  max_class_lines: 500
  max_cyclomatic_complexity: 10

  # 命名規則チェック
  naming_conventions:
    private_fields: "_camelCase"
    public_properties: "PascalCase"
    methods: "PascalCase"
    constants: "UPPER_SNAKE_CASE"
    interfaces: "IPascalCase"

# ChatOps 設定（@coderabbit コマンドの扱い）
chat:
  enabled: true
  trigger_phrases:
    - "@coderabbit"
    - "@ai"
    - "@review"

  # カスタムコマンド
  custom_commands:
    - command: "@coderabbit check-mvvm"
      description: "MVVMパターンの遵守をチェック"
    - command: "@coderabbit check-coding-rules"
      description: "コーディング規則の遵守をチェック"
    - command: "@coderabbit performance"
      description: "パフォーマンスに関する問題をチェック"

# ラベル自動付与
labels:
  auto_assign: true
  mappings:
    # 変更タイプに応じたラベル
    - pattern: "**/Models/**"
      label: "MVVM:Model"
    - pattern: "**/Views/**"
      label: "MVVM:View"
    - pattern: "**/ViewModels/**"
      label: "MVVM:ViewModel"
    - pattern: "**/Services/**"
      label: "service"
    - pattern: "**/Tests/**"
      label: "tests"

    # 機能に応じたラベル
    - pattern: "**/Combat/**"
      label: "combat-system"
    - pattern: "**/Replay/**"
      label: "replay-system"
    - pattern: "**/Customization/**"
      label: "customization"
    - pattern: "**/Multiplayer/**"
      label: "multiplayer"

    # サイズラベル
    - lines_changed: 1-50
      label: "size/XS"
    - lines_changed: 51-200
      label: "size/S"
    - lines_changed: 201-500
      label: "size/M"
    - lines_changed: 501-1000
      label: "size/L"
    - lines_changed: 1001+
      label: "size/XL"

# レビュー品質向上設定
review_quality:
  # コーディング規則ドキュメントを参照
  reference_docs:
    - path: "Docs/CODING_RULES.md"
      description: "プロジェクトのコーディング規則"
    - path: ".github/CONTRIBUTING.md"
      description: "貢献ガイドライン"

  # 重点的にチェックする項目
  focus_areas:
    - mvvm_pattern_adherence
    - nullable_reference_types
    - regions_organization
    - xml_documentation
    - namespace_conventions
    - performance_best_practices
    - unity_best_practices

# 通知設定
notifications:
  # 重要な問題のみ通知
  severity_threshold: warning

  # 通知するイベント
  events:
    - security_issue_found
    - performance_regression
    - coding_standard_violation
