#pragma warning disable IDE0032 // Use auto property

using AdvancedSceneManager.Models;
using System.Linq;
using UnityEngine;
using UnityEngine.UIElements;
using System.IO;
using System.Collections.Generic;
using System;
using System.Text;

#if UNITY_EDITOR
using UnityEditor;
using UnityEditor.Build;
using AdvancedSceneManager.Editor.Utility;
#endif

namespace AdvancedSceneManager.Core
{

#if ASM_DEV
    [CreateAssetMenu(fileName = "FeatureFlags", menuName = "Advanced Scene Manager/FeatureFlags")]
#endif
    internal class FeatureFlags : ScriptableObject
    {

        #region Instance

        static FeatureFlags m_instance;
        internal static FeatureFlags instance
        {
            get
            {
                if (!ASMSettings.instance)
                    return TempObj();

                m_temp = null; //We don't need temp object anymore, so lets just clear it. We only use it to prevent spam reads above.

                if (m_instance)
                    return m_instance;

                if (ASMSettings.instance.m_featureFlags)
                    return m_instance = ASMSettings.instance.m_featureFlags;

#if UNITY_EDITOR
                m_instance = ASMSettings.instance.m_featureFlags = AssetDatabaseUtility.FindAssets<FeatureFlags>().FirstOrDefault();
                ASMSettings.instance.SaveNow();
#endif

                if (!m_instance)
                    m_instance = TempObj();

                return m_instance;

            }
        }

        static FeatureFlags m_temp;
        static FeatureFlags TempObj()
        {
            if (m_temp)
                return m_temp;

            m_temp = CreateInstance<FeatureFlags>(); //Just disable all flags as a fallback
            m_temp.hideFlags = HideFlags.DontSave;
            return m_temp;
        }

        #endregion
        #region Uss generation

        [SerializeField] private StyleSheet m_styleSheet_dev;
        [SerializeField] private StyleSheet m_styleSheet_prod;

#if ASM_DEV
        public StyleSheet styleSheet => m_styleSheet_dev;
#else
        public StyleSheet styleSheet => m_styleSheet_prod;
#endif

#if UNITY_EDITOR

        public void GenerateStyleSheets()
        {
            GenerateStyleSheet(m_styleSheet_dev, dev: true);
            GenerateStyleSheet(m_styleSheet_prod, dev: false);
        }

        void GenerateStyleSheet(StyleSheet sheet, bool dev)
        {

            // Only generate if we have a saved asset on disk
            if (!sheet || !EditorUtility.IsPersistent(sheet))
                return;

            string path = AssetDatabase.GetAssetPath(sheet);
            if (string.IsNullOrEmpty(path))
                return;

            var sb = new StringBuilder();
            sb.AppendLine("/* Auto-generated by FeatureFlags.GenerateStyleSheet() */");
            sb.AppendLine();

            foreach (var flag in Enumerate())
            {
                sb.AppendLine($".{flag.effectiveName} {{");
                sb.AppendLine($"    display: {(flag.enabled && dev ? "flex" : "none")};");
                sb.AppendLine("}");
                sb.AppendLine();
            }

            File.WriteAllText(path, sb.ToString());
            AssetDatabase.ImportAsset(path);
            AssetDatabase.Refresh();

        }

#endif

        #endregion
        #region Apply scripting defines

#if UNITY_EDITOR

        public void ApplyScriptingDefines()
        {
            // Get the currently active build target
            var namedTarget = NamedBuildTarget.FromBuildTargetGroup(BuildPipeline.GetBuildTargetGroup(EditorUserBuildSettings.activeBuildTarget));

            // Get defines for that target
            var defines = PlayerSettings
                .GetScriptingDefineSymbols(namedTarget)
                .Split(';')
                .ToList();

            foreach (var flag in Enumerate())
                if (flag.enabled && !defines.Contains(flag.effectiveName))
                    defines.Add(flag.effectiveName);
                else if (!flag.enabled && defines.Contains(flag.effectiveName))
                    defines.Remove(flag.effectiveName);

            // Apply back to PlayerSettings
            PlayerSettings.SetScriptingDefineSymbols(namedTarget, string.Join(";", defines));
        }

#endif

        #endregion

        public List<FeatureFlag> flags = new();

        public IEnumerable<FeatureFlag> Enumerate() => flags.Distinct();

        private static string SanitizeName(string input)
        {
            if (string.IsNullOrWhiteSpace(input))
                return string.Empty;

            input = input.Trim();
            input = input.ToUpperInvariant();
            input = System.Text.RegularExpressions.Regex.Replace(input, @"[^A-Z0-9_-]", "_");

            if (!char.IsLetter(input, 0) && input[0] != '_')
                input = "_" + input;

            return input;
        }

        public static string GetEffectiveName(string input)
        {
            if (string.IsNullOrWhiteSpace(input))
                return string.Empty;

            var sanitized = SanitizeName(input);

            // Avoid double-prefixing
            return sanitized.StartsWith("ASM_") ? sanitized : "ASM_" + sanitized;
        }

        [System.Serializable]
        public class FeatureFlag : IEquatable<FeatureFlag>, ISerializationCallbackReceiver
        {

            public string name;
            public bool enabled;

            public string effectiveName => GetEffectiveName(name);

            public FeatureFlag(string name, bool enabled)
            {
                this.name = name;
                this.enabled = enabled;
            }

            #region Equality

            public bool Equals(FeatureFlag other)
            {
                if (other is null)
                    return false;
                if (ReferenceEquals(this, other))
                    return true;
                return string.Equals(name, other.name, System.StringComparison.OrdinalIgnoreCase);
            }

            public override bool Equals(object obj) =>
                Equals(obj as FeatureFlag);

            public override int GetHashCode() =>
                name?.ToUpperInvariant().GetHashCode() ?? 0;

            public static bool operator ==(FeatureFlag left, FeatureFlag right) =>
                Equals(left, right);

            public static bool operator !=(FeatureFlag left, FeatureFlag right) =>
                !Equals(left, right);

            #endregion
            #region ISerializationCallbackReceiver

            void ISerializationCallbackReceiver.OnBeforeSerialize()
            {
                name = effectiveName;
            }

            void ISerializationCallbackReceiver.OnAfterDeserialize()
            {
                name = effectiveName;
            }

            #endregion

        }

    }

}
